"""
Realtime AI Routes
==================

Real-time speech-to-speech endpoints for live voice agents (Wanderlaut /
Tscheppaschlucht Guide and similar live-conversation use-cases).

Architecture
------------

The browser opens a WebRTC peer connection straight to the upstream
provider (OpenAI Realtime, ElevenLabs Conversational AI). We never
proxy audio through api-ai — the latency budget would not survive it.

What api-ai *does* serve:
  * ``POST /ai/realtime/token`` — ephemeral token mint with embedded
    function definitions and a cost-gate (default-deny + 100 EUR/month
    shared cap). The browser uses this token for the SDP offer.
  * ``POST /ai/realtime/tool/{tool_name}`` — proxy for the Read tools
    the model calls during a session (``knowledge_query``, ``pois_near``,
    etc). The browser receives ``function_call`` events from the WebRTC
    data channel and POSTs them here. Display-hint tools never reach
    this endpoint — they are short-circuited in the browser by
    GuideDevBot2's ``RealtimeFunctionRouter`` (Content-Post #1196).
  * ``GET /ai/realtime/cost-status`` — federation-shared cap state.
  * ``POST /ai/realtime/usage`` — post-session usage callback from the
    browser so the cost tracker sees audio/text token counts.
  * ``POST /ai/realtime/cost-status/reset-hard-cap`` — same operator
    escape hatch as the other cost-tracker endpoints.

Federation contract (Content-Post #1196 consensus, 2026-06-22):

  Tool-type    | Routing
  -------------|------------------------------------------------------
  Read         | browser → POST /ai/realtime/tool/{name} → AiApi → MCP
  Persist      | browser → POST guide-api /api/v1/realtime/narration
  Display-hint | browser stays local: function_call → _bus.emit(...)

The token returned by ``/ai/realtime/token`` carries the full tool list
so the browser only ever decides routing, not whether a tool exists.
"""
from __future__ import annotations

import logging
import os
import time
from typing import Any, List, Optional

import httpx
from fastapi import APIRouter, Depends, HTTPException, Header, Path
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)
router = APIRouter()


# ── Models ────────────────────────────────────────────────────────────


# Supported realtime model IDs. The full list mirrors what api-ai is
# wired to mint tokens against; the browser picks one when it asks for
# a token. Adding a new model means: (1) add it here, (2) add pricing
# to ``openai_realtime_cost_tracker.OPENAI_REALTIME_PRICING``.
SUPPORTED_REALTIME_MODELS = {
    "gpt-realtime",                     # default upgrade, premium voice
    "gpt-4o-realtime-preview",
    "gpt-4o-mini-realtime-preview",     # MVP — cheapest, 6x less than gpt-realtime
}

DEFAULT_REALTIME_MODEL = "gpt-4o-mini-realtime-preview"

# Voices OpenAI Realtime exposes today. The browser can pick or default.
DEFAULT_REALTIME_VOICE = "marin"
SUPPORTED_REALTIME_VOICES = {
    "alloy", "ash", "ballad", "coral", "echo", "marin", "sage", "shimmer", "verse",
}


class RealtimeTokenRequest(BaseModel):
    """Body for ``POST /ai/realtime/token``.

    The session_id is generated by guide-api at ``/api/v1/realtime/session/start``
    and threaded through here so the issued token carries it as metadata
    — useful for downstream attribution on the ``/tool/{name}`` proxy
    and for the usage callback.
    """

    model: Optional[str] = Field(
        default=DEFAULT_REALTIME_MODEL,
        description=(
            "Realtime model. Default 'gpt-4o-mini-realtime-preview' for the MVP "
            "(cheap, multilingual DE/SL/IT/EN). 'gpt-realtime' for premium voice."
        ),
    )
    voice: Optional[str] = Field(
        default=DEFAULT_REALTIME_VOICE,
        description=f"Voice id, one of {sorted(SUPPORTED_REALTIME_VOICES)}.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description=(
            "Guide-api session id. Echoed in the token's session metadata "
            "and required on every /ai/realtime/tool/{name} call so the "
            "proxy can attribute tool use to the right session."
        ),
    )
    track_id: Optional[int] = Field(
        default=None,
        description="ArTrack track id (for pre-warm Knowledge/POI caches).",
    )
    language: Optional[str] = Field(
        default="de",
        description="Primary spoken language hint. de|sl|it|en.",
    )
    instructions: Optional[str] = Field(
        default=None,
        description=(
            "Override the default Wanderlaut-Guide system prompt. If null, "
            "api-ai injects a sensible default that wires the model up to "
            "the Federation tool set and tells it when to persist."
        ),
    )
    confirm_api_billing: Optional[bool] = Field(
        default=False,
        description=(
            "Default-deny billing gate (OpenAI Realtime is PAYG, 100 EUR/month "
            "federation-shared cap). Must be true to mint a token."
        ),
    )
    persona_variant: Optional[str] = Field(
        default=None,
        description=(
            "Federation virtual-bot persona to layer into the system prompt "
            "(same scheme as /ai/{claude,chatgpt,gemini}). Optional."
        ),
    )


class RealtimeUsageReport(BaseModel):
    """Body for ``POST /ai/realtime/usage`` — the browser reports the
    final usage block it received from OpenAI's ``response.done`` events
    so the cost-tracker sees real numbers."""

    model: str
    session_id: Optional[str] = None
    audio_input_tokens: int = 0
    audio_output_tokens: int = 0
    text_input_tokens: int = 0
    text_output_tokens: int = 0
    duration_sec: float = 0.0


class RealtimeToolCall(BaseModel):
    """Body for ``POST /ai/realtime/tool/{tool_name}`` — the browser
    forwards a ``function_call`` it received over the WebRTC data
    channel here. ``arguments`` is the model's JSON-decoded payload."""

    arguments: dict = Field(default_factory=dict)
    call_id: Optional[str] = Field(
        default=None,
        description="OpenAI's tool-call id, echoed back unchanged.",
    )


# ── Function definitions ──────────────────────────────────────────────


def _read_tool_defs() -> List[dict]:
    """Read-tools: data the model fetches mid-conversation. Function
    calls land at ``POST /ai/realtime/tool/{name}`` and are proxied to
    the Federation MCPs. Kept minimal — three slots cover the Tscheppa
    use case; more can be added without a schema rebuild because OpenAI
    accepts arbitrary tools in the session config."""
    return [
        {
            "type": "function",
            "name": "knowledge_query",
            "description": (
                "Search the Knowledge base for posts near the user's location "
                "or matching a query. Use this when the user asks 'what is...' "
                "about flora/fauna/sights or you need to confirm a fact before "
                "speaking. Results include title, summary, and storage_id for "
                "images that can be passed to show_image."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "Free-text question or species name."},
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                    "radius_m": {"type": "number", "description": "Optional. Default 500m."},
                    "limit": {"type": "integer", "description": "Optional. Default 5."},
                },
                "required": ["query"],
            },
        },
        {
            "type": "function",
            "name": "pois_near",
            "description": (
                "Return ArTrack waypoints / POIs near the given GPS. Use to "
                "name what's at the user's location or what's coming up next."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                    "radius_m": {"type": "number", "description": "Default 200m."},
                    "track_id": {"type": "integer", "description": "Optional ArTrack track scope."},
                },
                "required": ["lat", "lon"],
            },
        },
        {
            "type": "function",
            "name": "narration_near",
            "description": (
                "Look up previously persisted narration_points near the user. "
                "Use this BEFORE generating a fresh description so you can "
                "build on existing context instead of re-inventing."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                    "radius_m": {"type": "number", "description": "Default 100m."},
                },
                "required": ["lat", "lon"],
            },
        },
    ]


def _persist_tool_defs() -> List[dict]:
    """Persist-tools: writes into the durable narration corpus. The
    browser routes these to guide-api's
    ``POST /api/v1/realtime/narration`` (NOT through AiApi) per
    Content-Post #1196 consensus."""
    return [
        {
            "type": "function",
            "name": "persist_narration",
            "description": (
                "Persist this narration segment to the deterministic corpus "
                "so other users can replay it at the same GPS later. Call "
                "EVERY TIME you finish describing a place. Idempotent via "
                "(lat, lon, title)."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {"type": "string", "description": "POI / waypoint name."},
                    "text": {"type": "string", "description": "Narration text, 1-3 sentences."},
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                    "language": {
                        "type": "string",
                        "enum": ["de", "sl", "it", "en"],
                        "description": "Optional, default de.",
                    },
                },
                "required": ["title", "text", "lat", "lon"],
            },
        },
    ]


def _display_hint_tool_defs() -> List[dict]:
    """Display-hint tools: short-circuited in the browser. The function
    call result is `_bus.emit(topic|images|knowledge|map)`'d straight
    into the existing Wanderlaut UI; no backend roundtrip.

    The model still benefits from declaring them so it actually emits
    the calls. The browser's RealtimeFunctionRouter (GuideDevBot2) is
    in charge of recognising the tool names and skipping the proxy."""
    return [
        {
            "type": "function",
            "name": "show_topic",
            "description": (
                "Display this topic-card in the UI (title + optional GPS pin "
                "on map). Call when you START describing a new POI."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                },
                "required": ["title"],
            },
        },
        {
            "type": "function",
            "name": "show_image",
            "description": (
                "Display an image in the gallery panel. Use storage_id from "
                "knowledge_query results."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "storage_id": {"type": "integer"},
                    "caption": {"type": "string"},
                },
                "required": ["storage_id"],
            },
        },
        {
            "type": "function",
            "name": "show_knowledge_pin",
            "description": (
                "Highlight a knowledge_post in the side panel (e.g. fauna "
                "species the user asked about)."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "knowledge_post_id": {"type": "integer"},
                },
                "required": ["knowledge_post_id"],
            },
        },
        {
            "type": "function",
            "name": "focus_map",
            "description": (
                "Pan/zoom the map to these coordinates. Call when you "
                "reference a place the user can't see yet."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                    "zoom": {"type": "number"},
                },
                "required": ["lat", "lon"],
            },
        },
    ]


def _all_tool_defs() -> List[dict]:
    return _read_tool_defs() + _persist_tool_defs() + _display_hint_tool_defs()


def _default_instructions(language: str = "de", track_id: Optional[int] = None) -> str:
    """System prompt that wires the model into the Federation tool set."""
    track_hint = (
        f"You are guiding the user through ArTrack track #{track_id}. "
        if track_id else ""
    )
    return (
        "You are the Wanderlaut Voice-Guide, a calm, knowledgeable companion "
        "for hikers in the Tscheppaschlucht and nearby trails. "
        f"{track_hint}"
        "Default language is "
        f"{ {'de': 'German', 'sl': 'Slovenian', 'it': 'Italian', 'en': 'English'}.get(language, 'German') }, "
        "but mirror the user's language when they switch. Keep replies "
        "short (1-3 sentences) and conversational; never lecture.\n\n"
        "TOOL DISCIPLINE — this is critical:\n"
        "  * ALWAYS call `knowledge_query` or `narration_near` BEFORE making "
        "a factual claim about a POI, plant or animal. Never invent details.\n"
        "  * Call `show_topic` the moment you start describing a new place, "
        "and `show_image` whenever knowledge_query returns a storage_id.\n"
        "  * Call `persist_narration` AFTER you finish describing a place — "
        "this saves what you said for other users.\n"
        "  * If a tool will take noticeable time, say 'Moment...' so the user "
        "knows you're working, then continue.\n\n"
        "Voice: warm, slightly poetic, occasionally playful. Never robotic."
    )


# ── Billing gate ──────────────────────────────────────────────────────


def _check_realtime_billing_gate(confirmed: Optional[bool]) -> None:
    """Default-deny + monthly-cap gate, mirrors the M3/DeepSeek/OpenAI
    pattern. 403 when caller forgot the flag, 429 when the 100 EUR cap
    has been blown for the month."""
    from ..services.openai_realtime_cost_tracker import openai_realtime_cost_tracker

    if not confirmed:
        raise HTTPException(
            status_code=403,
            detail={
                "error": "api_billing_confirmation_required",
                "endpoint": "openai-realtime",
                "provider": "openai",
                "hint": (
                    "OpenAI Realtime is pay-as-you-go billed against "
                    "OPENAI_API_KEY (~$0.05-0.30/minute depending on model). "
                    "Federation-shared 100 EUR/month cap. Send "
                    "`confirm_api_billing: true` to acknowledge."
                ),
            },
        )
    if openai_realtime_cost_tracker.should_block_request():
        status = openai_realtime_cost_tracker.get_status()
        raise HTTPException(
            status_code=429,
            detail={
                "error": "monthly_api_cap_reached",
                "endpoint": "openai-realtime",
                "provider": "openai",
                "spent_eur": round(status.get("total_cost_eur", 0.0), 2),
                "budget_eur": status.get("monthly_budget_eur"),
                "hint": (
                    "OpenAI Realtime monthly cap reached. Cap resets at the "
                    "start of the next calendar month. Other endpoints "
                    "(/ai/claude, /ai/chatgpt, image gen) are unaffected."
                ),
            },
        )


def get_api_key():  # placeholder, mirrors other routes
    return "placeholder"


# ── Endpoints ─────────────────────────────────────────────────────────


@router.post("/realtime/token")
async def mint_realtime_token(
    request: RealtimeTokenRequest,
    api_key: str = Depends(get_api_key),
):
    """Mint a short-lived OpenAI Realtime session token.

    Returns the raw OpenAI ephemeral token plus the resolved model and
    tool list so the browser knows exactly what the session config
    will look like.
    """
    _check_realtime_billing_gate(request.confirm_api_billing)

    model = request.model or DEFAULT_REALTIME_MODEL
    if model not in SUPPORTED_REALTIME_MODELS:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "unsupported_realtime_model",
                "model": model,
                "supported": sorted(SUPPORTED_REALTIME_MODELS),
            },
        )

    voice = request.voice or DEFAULT_REALTIME_VOICE
    if voice not in SUPPORTED_REALTIME_VOICES:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "unsupported_realtime_voice",
                "voice": voice,
                "supported": sorted(SUPPORTED_REALTIME_VOICES),
            },
        )

    instructions = request.instructions or _default_instructions(
        language=request.language or "de",
        track_id=request.track_id,
    )

    # Federation persona — optional. Uses the same get_persona_bundle
    # helper as the text routes so the same virtual-bots that work
    # against /ai/claude work against /ai/realtime too.
    persona_rendered = ""
    if request.persona_variant:
        try:
            from .text_ai_routes import get_persona_bundle
            persona = await get_persona_bundle("realtime", request.persona_variant)
            persona_rendered = persona.get("rendered", "")
            if persona_rendered:
                instructions = f"{persona_rendered}\n\n{instructions}"
                logger.info(
                    f"Realtime: injected persona "
                    f"api-ai-realtime-{request.persona_variant} "
                    f"({len(persona_rendered)} chars)"
                )
        except Exception as e:
            logger.warning(f"Realtime: persona fetch failed ({e}); proceeding without")

    api_key_env = os.getenv("OPENAI_API_KEY", "")
    if not api_key_env:
        raise HTTPException(
            status_code=500,
            detail={
                "error": "openai_api_key_missing",
                "hint": "OPENAI_API_KEY not configured in service env.",
            },
        )

    tools = _all_tool_defs()
    # OpenAI's GA Realtime session shape (2025-Q4+) nests audio knobs
    # under ``audio.input`` / ``audio.output`` instead of the legacy
    # flat ``voice`` / ``input_audio_format`` fields. The mint endpoint
    # surfaces "Unknown parameter: 'session.voice'" when you use the
    # old layout, so we ship the new layout from day one.
    session_config = {
        "type": "realtime",
        "model": model,
        "instructions": instructions,
        "tools": tools,
        "audio": {
            "input": {
                "format": {"type": "audio/pcm", "rate": 24000},
                "transcription": {"model": "whisper-1"},
                "turn_detection": {
                    "type": "server_vad",
                    "threshold": 0.5,
                    "silence_duration_ms": 500,
                },
            },
            "output": {
                "format": {"type": "audio/pcm", "rate": 24000},
                "voice": voice,
            },
        },
    }
    # NOTE: session.metadata is not (yet?) accepted on the
    # client_secrets mint — we drop it from the session-config and
    # stamp guide_session_id / track_id only in our own response, where
    # the browser already needs to read it to wire X-Session-ID headers.

    # Token-mint upstream — OpenAI's /v1/realtime/client_secrets endpoint
    # returns an ephemeral client secret with the session_config baked in.
    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            r = await client.post(
                "https://api.openai.com/v1/realtime/client_secrets",
                json={"session": session_config},
                headers={
                    "Authorization": f"Bearer {api_key_env}",
                    "OpenAI-Beta": "realtime=v1",
                },
            )
        except httpx.HTTPError as e:
            raise HTTPException(
                status_code=502,
                detail={
                    "error": "openai_upstream_unreachable",
                    "exc": str(e)[:200],
                },
            )

    if r.status_code >= 400:
        try:
            upstream = r.json()
        except Exception:
            upstream = {"raw": r.text[:500]}
        logger.error(
            f"OpenAI realtime token mint failed {r.status_code}: {upstream}"
        )
        raise HTTPException(
            status_code=502 if r.status_code >= 500 else r.status_code,
            detail={
                "error": "openai_upstream_error",
                "upstream_status": r.status_code,
                "upstream_body": upstream,
            },
        )

    body = r.json()

    # Track the session-start before we hand the token to the browser.
    # The actual usage roll-up arrives later via /ai/realtime/usage.
    from ..services.openai_realtime_cost_tracker import openai_realtime_cost_tracker
    openai_realtime_cost_tracker.track_session_start()

    return {
        "client_secret": body.get("client_secret") or body.get("value") or body,
        "expires_at": body.get("expires_at"),
        "model": model,
        "voice": voice,
        "tools": [t["name"] for t in tools],
        "session_id": request.session_id,
        "raw": body,
    }


@router.get("/realtime/models")
async def list_realtime_models():
    """Return the realtime models and voices we support."""
    return {
        "models": [
            {
                "id": "gpt-4o-mini-realtime-preview",
                "provider": "openai",
                "default": True,
                "tier": "mvp",
                "description": (
                    "Cheap, multilingual (DE/SL/IT/EN), 300-500ms roundtrip. "
                    "Recommended for the Tscheppa spike."
                ),
                "price_per_min_usd_estimate": "$0.05-0.10",
            },
            {
                "id": "gpt-realtime",
                "provider": "openai",
                "tier": "premium",
                "description": (
                    "Best voice quality, lower roundtrip latency. Upgrade "
                    "from mini once the spike is validated."
                ),
                "price_per_min_usd_estimate": "$0.15-0.30",
            },
            {
                "id": "gpt-4o-realtime-preview",
                "provider": "openai",
                "tier": "legacy-preview",
                "description": "Older preview model, kept for migration only.",
                "price_per_min_usd_estimate": "$0.20-0.40",
            },
        ],
        "voices": sorted(SUPPORTED_REALTIME_VOICES),
        "tools": [
            {"name": t["name"], "description": t["description"]}
            for t in _all_tool_defs()
        ],
    }


@router.get("/realtime/cost-status")
async def realtime_cost_status():
    """Federation-shared Realtime cap state, same shape as the other
    /ai/{provider}/cost-status endpoints."""
    from ..services.openai_realtime_cost_tracker import openai_realtime_cost_tracker
    return openai_realtime_cost_tracker.get_status()


@router.post("/realtime/cost-status/reset-hard-cap")
async def reset_realtime_hard_cap(api_key: str = Depends(get_api_key)):
    """Operator escape hatch — clears the persistent hard-cap flag.

    Mirror of ``/ai/gemini/cost-status/reset-hard-cap``. The cap will
    re-trip automatically if usage tracking puts us back over 100 EUR,
    so this is safe to call without risking silent re-opening.
    """
    from ..services.openai_realtime_cost_tracker import openai_realtime_cost_tracker
    result = openai_realtime_cost_tracker.clear_hard_cap()
    logger.warning(
        f"Realtime hard-cap manually reset (was_active={result['was_active']})"
    )
    return result


@router.post("/realtime/usage")
async def realtime_usage_report(report: RealtimeUsageReport):
    """Browser-reported usage callback.

    OpenAI Realtime emits ``response.done`` events with a usage block:
    ``input_tokens.audio_tokens``, ``output_tokens.audio_tokens``, plus
    the text-token mirror. The browser sums these across the session
    and POSTs the totals here at session-end.

    No auth gate — the cost tracker is the source of truth, and
    over-reporting only hurts the caller's own cap.
    """
    from ..services.openai_realtime_cost_tracker import openai_realtime_cost_tracker
    openai_realtime_cost_tracker.track_session(
        model=report.model,
        audio_input_tokens=report.audio_input_tokens,
        audio_output_tokens=report.audio_output_tokens,
        text_input_tokens=report.text_input_tokens,
        text_output_tokens=report.text_output_tokens,
        duration_sec=report.duration_sec,
    )
    return openai_realtime_cost_tracker.get_status()


# ── Tool-routing proxy ────────────────────────────────────────────────


# Allowed Read tools — the only ones the browser is supposed to route
# through AiApi. Display-hint tools must NEVER reach this endpoint
# (the browser shorts them locally); we reject them so a bug there
# surfaces fast instead of silently going to OpenAI's expensive
# fail-mode of "model thinks it called the tool, never got an answer".
READ_TOOL_NAMES = {"knowledge_query", "pois_near", "narration_near"}


@router.post("/realtime/tool/{tool_name}")
async def realtime_tool_call(
    tool_name: str = Path(..., description="Function name from the model"),
    body: RealtimeToolCall = ...,
    x_session_id: Optional[str] = Header(
        default=None,
        alias="X-Session-ID",
        description="Guide-api session id, stamped by the browser.",
    ),
):
    """Resolve a Realtime function-call against the Federation MCPs.

    The browser receives a ``function_call`` event from the data
    channel, JSON-decodes the ``arguments``, and POSTs them here. We
    dispatch by tool name, talk to the appropriate Federation service,
    and return a JSON result that the browser forwards back to OpenAI
    as the ``function_call_output``. OpenAI then resumes generation
    with the new context.

    Latency budget: <= 250ms end-to-end is the target. Anything slower
    causes a hearable hang in the spoken response. We rely on the
    Federation MCPs being colocated on arkserver / arkturian, and a
    hot httpx client at runtime.
    """
    if tool_name not in READ_TOOL_NAMES:
        raise HTTPException(
            status_code=400,
            detail={
                "error": "tool_not_routable_via_aiapi",
                "tool": tool_name,
                "hint": (
                    "Display-hint tools (show_*, focus_map) must be "
                    "handled in the browser by emitting _bus events. "
                    "Persist tools (persist_narration) must POST to "
                    "guide-api /api/v1/realtime/narration directly. "
                    "Only Read tools route through AiApi: "
                    f"{sorted(READ_TOOL_NAMES)}."
                ),
            },
        )

    t0 = time.monotonic()
    args = body.arguments or {}
    result: Any
    try:
        if tool_name == "knowledge_query":
            result = await _tool_knowledge_query(args)
        elif tool_name == "pois_near":
            result = await _tool_pois_near(args)
        elif tool_name == "narration_near":
            result = await _tool_narration_near(args)
        else:
            # Defensive: should be caught by READ_TOOL_NAMES check above.
            raise HTTPException(status_code=400, detail="unknown tool")
    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"realtime tool {tool_name} failed: {e}")
        # Return a structured tool error to OpenAI so the model can
        # apologise verbally instead of stalling.
        return {
            "call_id": body.call_id,
            "tool": tool_name,
            "ok": False,
            "error": str(e)[:200],
            "elapsed_ms": int((time.monotonic() - t0) * 1000),
        }

    elapsed_ms = int((time.monotonic() - t0) * 1000)
    if elapsed_ms > 250:
        logger.warning(
            f"realtime tool {tool_name} took {elapsed_ms}ms — "
            f"may cause hearable hang"
        )
    logger.info(
        f"realtime tool {tool_name} ok in {elapsed_ms}ms "
        f"(session={x_session_id})"
    )
    return {
        "call_id": body.call_id,
        "tool": tool_name,
        "ok": True,
        "result": result,
        "elapsed_ms": elapsed_ms,
    }


# ── Tool implementations ──────────────────────────────────────────────


def _knowledge_api_base() -> str:
    return os.getenv(
        "KNOWLEDGE_API_URL", "https://knowledge-api.arkturian.com"
    ).rstrip("/")


def _artrack_api_base() -> str:
    return os.getenv(
        "ARTRACK_API_URL", "https://artrack-api.arkturian.com"
    ).rstrip("/")


def _guide_api_base() -> str:
    return os.getenv(
        "GUIDE_API_URL", "https://guide-api.arkturian.com"
    ).rstrip("/")


async def _tool_knowledge_query(args: dict) -> dict:
    """Wraps ``mcp__knowledge__knowledge_query``.

    We hit the HTTP endpoint directly rather than going through the
    MCP-server so the latency stays under control. The MCP layer adds
    a tmux-bot roundtrip we cannot afford during a live conversation.
    """
    query = args.get("query") or ""
    if not query:
        raise HTTPException(status_code=400, detail="knowledge_query: 'query' required")
    payload = {
        "query": query,
        "limit": int(args.get("limit", 5)),
    }
    if "lat" in args and "lon" in args:
        payload["lat"] = float(args["lat"])
        payload["lon"] = float(args["lon"])
        payload["radius_m"] = float(args.get("radius_m", 500))
    async with httpx.AsyncClient(timeout=2.0) as client:
        r = await client.post(
            f"{_knowledge_api_base()}/api/v1/knowledge/query",
            json=payload,
        )
        r.raise_for_status()
        data = r.json()
    # Trim to what the model can speak about — title + summary + storage_id
    # for image hand-off.
    items = []
    for it in (data.get("items") or [])[: payload["limit"]]:
        items.append({
            "id": it.get("id"),
            "title": it.get("title"),
            "summary": (it.get("summary") or it.get("excerpt") or "")[:280],
            "binom": it.get("binom"),
            "storage_id": it.get("hero_storage_id") or it.get("storage_id"),
            "lat": it.get("lat"),
            "lon": it.get("lon"),
        })
    return {"items": items, "count": len(items)}


async def _tool_pois_near(args: dict) -> dict:
    """Wraps ``mcp__artrack__pois_near`` / ``waypoints near``."""
    lat = float(args["lat"])
    lon = float(args["lon"])
    radius_m = float(args.get("radius_m", 200))
    params = {"lat": lat, "lon": lon, "radius_m": radius_m}
    if "track_id" in args:
        params["track_id"] = int(args["track_id"])
    async with httpx.AsyncClient(timeout=2.0) as client:
        r = await client.get(
            f"{_artrack_api_base()}/api/v1/waypoints/near", params=params
        )
        r.raise_for_status()
        data = r.json()
    items = []
    for wp in (data.get("waypoints") or data.get("items") or [])[:10]:
        items.append({
            "id": wp.get("id"),
            "title": wp.get("title") or wp.get("name"),
            "category": wp.get("category") or wp.get("type"),
            "lat": wp.get("lat"),
            "lon": wp.get("lon"),
            "distance_m": wp.get("distance_m"),
            "knowledge_id": wp.get("knowledge_id"),
        })
    return {"items": items, "count": len(items)}


async def _tool_narration_near(args: dict) -> dict:
    """Wraps guide-api narration-near lookup. Owned by GuideDevBot's
    wrapper endpoint; we POST to ``/api/v1/realtime/narration/near``
    (the dual to ``/api/v1/realtime/narration``)."""
    lat = float(args["lat"])
    lon = float(args["lon"])
    radius_m = float(args.get("radius_m", 100))
    async with httpx.AsyncClient(timeout=2.0) as client:
        r = await client.get(
            f"{_guide_api_base()}/api/v1/realtime/narration/near",
            params={"lat": lat, "lon": lon, "radius_m": radius_m},
        )
        # 404 = endpoint not deployed yet (GuideDevBot's side). Return an
        # empty result so the model can proceed rather than failing the
        # whole tool-call chain.
        if r.status_code == 404:
            logger.info(
                "narration_near: guide-api endpoint 404 — "
                "GuideDevBot wrapper not deployed yet, returning empty"
            )
            return {"items": [], "count": 0, "note": "guide-api endpoint pending"}
        r.raise_for_status()
        data = r.json()
    return {
        "items": data.get("items", []),
        "count": data.get("count", 0),
    }
